MDScreen:

    name:'Contact'
    MDFloatLayout:
        md_bg_color:1,1,1,1
        MDIconButton:
            icon:'chevron-left'
            user_font_size:'35sp'
            pos_hint:{'center_y':.95}
            on_release:app.Contact_back()
        MDLabel:
            text:'Back'
            font_size:'18sp'
            font_name:'Poppins-SemiBold.ttf'
            pos_hint:{'center_x':.55,'center_y':.949}

